# Generated by Django 4.2.28 on 2026-02-27 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0033_add_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jsonconfig',
            name='movieGenerationStatus',
        ),
        migrations.RemoveField(
            model_name='jsonconfig',
            name='movieHorizontal',
        ),
        migrations.RemoveField(
            model_name='jsonconfig',
            name='movieVertical',
        ),
    ]
