# Generated by Django 4.2.28 on 2026-03-24 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0034_jsonconfig_hidepie'),
        ('visualizer', '0034_remove_movie_fields'),
    ]

    operations = [
    ]
